# Copyright (c) 2016-2022, Thomas Larsson
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.

from .layers import *

MhxSkeleton = {
    "hip" : ("hip", L_MAIN),
    "pelvis" : ("pelvis", L_SPINE),
    "abdomen" : ("spine", L_SPINE),
    "abdomenLower" : ("spine", L_SPINE),
    "spine1" : ("spine", L_SPINE),
    "abdomen2" : ("spine-1", L_SPINE),
    "abdomenUpper" : ("spine-1", L_SPINE),
    "spine2" : ("spine-1", L_SPINE),
    "chest" : ("chest", L_SPINE),
    "chestLower" : ("chest", L_SPINE),
    "spine3" : ("chest", L_SPINE),
    "chestUpper" : ("chest-1", L_SPINE),
    "spine4" : ("chest-1", L_SPINE),
    "neck" : ("neck", L_SPINE),
    "neckLower" : ("neck", L_SPINE),
    "neck1" : ("neck", L_SPINE),
    "neckUpper" : ("neck-1", L_SPINE),
    "neck2" : ("neck-1", L_SPINE),
    "head" : ("head", L_SPINE),

    "tongue00" : ("tounge01", L_MAIN),
    "tongue02" : ("tongue02", L_MAIN),
    "tongue04" : ("tongue03", L_MAIN),
    "tongue06" : ("tongue04", L_MAIN),
    "lEye" : ("lEye", L_MAIN),
    "rEye" : ("rEye", L_MAIN),
    "leftEye" : ("lEye", L_MAIN),
    "rightEye" : ("rEye", L_MAIN),
    "l_eye" : ("lEye", L_MAIN),
    "r_eye" : ("rEye", L_MAIN),
    "lEar" : ("", L_MAIN),
    "rEar" : ("", L_MAIN),

    "lPectoral" : ("pectoral.L", L_LARMFK),
    "l_pectoral" : ("pectoral.L", L_LARMFK),
    "lCollar" : ("clavicle.L", L_LARMFK),
    "l_shoulder" : ("clavicle.L", L_LARMFK),
    "lShldr" : ("upper_arm.L", L_LARMFK),
    "lShldrBend" : ("upper_armBend.L", L_LARMFK),
    "lShldrTwist" : ("upper_armTwist.L", L_LARMFK),
    "l_upperarm" : ("upper_arm.L", L_LARMFK),
    "l_upperarmtwist1" : ("upper_arm.twist1.L", L_FIN),
    "l_upperarmtwist2" : ("upper_arm.twist2.L", L_FIN),
    "lForeArm" : ("forearm.L", L_LARMFK),
    "lForearmBend" : ("forearmBend.L", L_LARMFK),
    "lForearmTwist" : ("forearmTwist.L", L_LARMFK),
    "l_forearm" : ("forearm.L", L_LARMFK),
    "l_forearmtwist1" : ("forearm.twist1.L", L_FIN),
    "l_forearmtwist2" : ("forearm.twist2.L", L_FIN),
    "lHand" : ("hand.L", L_LARMFK),
    "l_hand" : ("hand.L", L_LARMFK),

    "rPectoral" : ("pectoral.R", L_RARMFK),
    "r_pectoral" : ("pectoral.R", L_RARMFK),
    "rCollar" : ("clavicle.R", L_RARMFK),
    "r_shoulder" : ("clavicle.R", L_RARMFK),
    "rShldr" : ("upper_arm.R", L_RARMFK),
    "rShldrBend" : ("upper_armBend.R", L_RARMFK),
    "rShldrTwist" : ("upper_armTwist.R", L_RARMFK),
    "r_upperarm" : ("upper_arm.R", L_RARMFK),
    "r_upperarmtwist1" : ("upper_arm.twist1.R", L_FIN),
    "r_upperarmtwist2" : ("upper_arm.twist2.R", L_FIN),
    "rForeArm" : ("forearm.R", L_RARMFK),
    "rForearmBend" : ("forearmBend.R", L_RARMFK),
    "rForearmTwist" : ("forearmTwist.R", L_RARMFK),
    "r_forearm" : ("forearm.R", L_RARMFK),
    "r_forearmtwist1" : ("forearm.twist1.R", L_FIN),
    "r_forearmtwist2" : ("forearm.twist2.R", L_FIN),
    "rHand" : ("hand.R", L_RARMFK),
    "r_hand" : ("hand.R", L_RARMFK),

    "lThigh" : ("thigh.L", L_LLEGFK),
    "lThighBend" : ("thighBend.L", L_LLEGFK),
    "lThighTwist" : ("thighTwist.L", L_LLEGFK),
    "l_thigh" : ("thigh.L", L_LLEGFK),
    "l_thightwist1" : ("thigh.twist1.L", L_FIN),
    "l_thightwist2" : ("thigh.twist2.L", L_FIN),
    "lShin" : ("shin.L", L_LLEGFK),
    "l_shin" : ("shin.L", L_LLEGFK),
    "lFoot" : ("foot.L", L_LLEGFK),
    "l_foot" : ("foot.L", L_LLEGFK),
    "lMetatarsals" : ("tarsal.L", L_LTOE),
    "l_metatarsal" : ("tarsal.L", L_LTOE),
    "lToe" : ("toe.L", L_LLEGFK),
    "l_toes" : ("toe.L", L_LLEGFK),
    "lHeel" : ("heel.L", L_LTOE),

    "rThigh" : ("thigh.R", L_RLEGFK),
    "rThighBend" : ("thighBend.R", L_RLEGFK),
    "rThighTwist" : ("thighTwist.R", L_RLEGFK),
    "r_thigh" : ("thigh.R", L_RLEGFK),
    "r_thightwist1" : ("thigh.twist1.R", L_FIN),
    "r_thightwist2" : ("thigh.twist2.R", L_FIN),
    "rShin" : ("shin.R", L_RLEGFK),
    "r_shin" : ("shin.R", L_RLEGFK),
    "rFoot" : ("foot.R", L_RLEGFK),
    "r_foot" : ("foot.R", L_RLEGFK),
    "rMetatarsals" : ("", L_RTOE),
    "r_metatarsal" : ("", L_RTOE),
    "rToe" : ("toe.R", L_RLEGFK),
    "r_toes" : ("toe.R", L_RLEGFK),
    "rHeel" : ("heel.R", L_RTOE),

    "lBigToe" : ("", L_LTOE),
    "lBigToe_2" : ("", L_LTOE),
    "lSmallToe1" : ("", L_LTOE),
    "lSmallToe1_2" : ("", L_LTOE),
    "lSmallToe2" : ("", L_LTOE),
    "lSmallToe2_2" : ("", L_LTOE),
    "lSmallToe3" : ("", L_LTOE),
    "lSmallToe3_2" : ("", L_LTOE),
    "lSmallToe4" : ("", L_LTOE),
    "lSmallToe4_2" : ("", L_LTOE),

    "rBigToe" : ("", L_RTOE),
    "rBigToe_2" : ("", L_RTOE),
    "rSmallToe1" : ("", L_RTOE),
    "rSmallToe1_2" : ("", L_RTOE),
    "rSmallToe2" : ("", L_RTOE),
    "rSmallToe2_2" : ("", L_RTOE),
    "rSmallToe3" : ("", L_RTOE),
    "rSmallToe3_2" : ("", L_RTOE),
    "rSmallToe4" : ("", L_RTOE),
    "rSmallToe4_2" : ("", L_RTOE),

    "lCarpal1" : ("palm_index.L", L_LFINGER),
    "lCarpal2" : ("palm_middle.L", L_LFINGER),
    "lCarpal3" : ("palm_ring.L", L_LFINGER),
    "lCarpal4" : ("palm_pinky.L", L_LFINGER),
    "l_indexmetacarpal" : ("palm_index.L", L_LFINGER),
    "l_midmetacarpal" : ("palm_middle.L", L_LFINGER),
    "l_ringmetacarpal" : ("palm_ring.L", L_LFINGER),
    "l_pinkymetacarpal" : ("palm_pinky.L", L_LFINGER),

    "rCarpal1" : ("palm_index.R", L_LFINGER),
    "rCarpal2" : ("palm_middle.R", L_LFINGER),
    "rCarpal3" : ("palm_ring.R", L_LFINGER),
    "rCarpal4" : ("palm_pinky.R", L_LFINGER),
    "r_indexmetacarpal" : ("palm_index.R", L_LFINGER),
    "r_midmetacarpal" : ("palm_middle.R", L_LFINGER),
    "r_ringmetacarpal" : ("palm_ring.R", L_LFINGER),
    "r_pinkymetacarpal" : ("palm_pinky.R", L_LFINGER),

    "lThumb1" : ("thumb.01.L", L_LFINGER),
    "lThumb2" : ("thumb.02.L", L_LFINGER),
    "lThumb3" : ("thumb.03.L", L_LFINGER),
    "lIndex1" : ("f_index.01.L", L_LFINGER),
    "lIndex2" : ("f_index.02.L", L_LFINGER),
    "lIndex3" : ("f_index.03.L", L_LFINGER),
    "lMid1" : ("f_middle.01.L", L_LFINGER),
    "lMid2" : ("f_middle.02.L", L_LFINGER),
    "lMid3" : ("f_middle.03.L", L_LFINGER),
    "lRing1" : ("f_ring.01.L", L_LFINGER),
    "lRing2" : ("f_ring.02.L", L_LFINGER),
    "lRing3" : ("f_ring.03.L", L_LFINGER),
    "lPinky1" : ("f_pinky.01.L", L_LFINGER),
    "lPinky2" : ("f_pinky.02.L", L_LFINGER),
    "lPinky3" : ("f_pinky.03.L", L_LFINGER),

    "l_thumb1" : ("thumb.01.L", L_LFINGER),
    "l_thumb2" : ("thumb.02.L", L_LFINGER),
    "l_thumb3" : ("thumb.03.L", L_LFINGER),
    "l_index1" : ("f_index.01.L", L_LFINGER),
    "l_index2" : ("f_index.02.L", L_LFINGER),
    "l_index3" : ("f_index.03.L", L_LFINGER),
    "l_mid1" : ("f_middle.01.L", L_LFINGER),
    "l_mid2" : ("f_middle.02.L", L_LFINGER),
    "l_mid3" : ("f_middle.03.L", L_LFINGER),
    "l_ring1" : ("f_ring.01.L", L_LFINGER),
    "l_ring2" : ("f_ring.02.L", L_LFINGER),
    "l_ring3" : ("f_ring.03.L", L_LFINGER),
    "l_pinky1" : ("f_pinky.01.L", L_LFINGER),
    "l_pinky2" : ("f_pinky.02.L", L_LFINGER),
    "l_pinky3" : ("f_pinky.03.L", L_LFINGER),

    "rThumb1" : ("thumb.01.R", L_RFINGER),
    "rThumb2" : ("thumb.02.R", L_RFINGER),
    "rThumb3" : ("thumb.03.R", L_RFINGER),
    "rIndex1" : ("f_index.01.R", L_RFINGER),
    "rIndex2" : ("f_index.02.R", L_RFINGER),
    "rIndex3" : ("f_index.03.R", L_RFINGER),
    "rMid1" : ("f_middle.01.R", L_RFINGER),
    "rMid2" : ("f_middle.02.R", L_RFINGER),
    "rMid3" : ("f_middle.03.R", L_RFINGER),
    "rRing1" : ("f_ring.01.R", L_RFINGER),
    "rRing2" : ("f_ring.02.R", L_RFINGER),
    "rRing3" : ("f_ring.03.R", L_RFINGER),
    "rPinky1" : ("f_pinky.01.R", L_RFINGER),
    "rPinky2" : ("f_pinky.02.R", L_RFINGER),
    "rPinky3" : ("f_pinky.03.R", L_RFINGER),

    "r_thumb1" : ("thumb.01.R", L_RFINGER),
    "r_thumb2" : ("thumb.02.R", L_RFINGER),
    "r_thumb3" : ("thumb.03.R", L_RFINGER),
    "r_index1" : ("f_index.01.R", L_RFINGER),
    "r_index2" : ("f_index.02.R", L_RFINGER),
    "r_index3" : ("f_index.03.R", L_RFINGER),
    "r_mid1" : ("f_middle.01.R", L_RFINGER),
    "r_mid2" : ("f_middle.02.R", L_RFINGER),
    "r_mid3" : ("f_middle.03.R", L_RFINGER),
    "r_ring1" : ("f_ring.01.R", L_RFINGER),
    "r_ring2" : ("f_ring.02.R", L_RFINGER),
    "r_ring3" : ("f_ring.03.R", L_RFINGER),
    "r_pinky1" : ("f_pinky.01.R", L_RFINGER),
    "r_pinky2" : ("f_pinky.02.R", L_RFINGER),
    "r_pinky3" : ("f_pinky.03.R", L_RFINGER)
}
